## 服务器配置
server:
  host: "127.0.0.1"
  port: 8089
  view_url: "http://localhost:8080/" ## 前端页面地址 用于跨域访问
  cms_url: "http://localhost:8080/" ## 后台页面地址 用于跨域访问
  token_expires: 7 # token 过期时间 单位:天
mysql:
  host: "127.0.0.1"
  port: 3306
  data_base: "zero_api"
  user_name: "root"
  password: "root"
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  username: ""
  password: ""
  #KEY 过期时间 单位:秒  -1:不过期
  ttl: -1
email:
  host: "smtp.qq.com"  #邮件服务器
  port: 465 #邮件端口
  username: "xxx@qq.com" 
  password: "xxxxxxx"  #授权码 