## log 配置
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"

  debug:
    kind: rolling_file
    path: "logs/debug.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"  
    policy:
      trigger:
        kind: size
        limit: 10MB
      roller:
        kind: fixed_window
        pattern: "logs/debug.{}.log"
        base: 0
        count: 10

  info:
    kind: rolling_file
    path: "logs/info.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10MB
      roller:
        kind: fixed_window
        pattern: "logs/info.{}.log"
        base: 0
        count: 10

#日志 root
root:
  level: INFO
  appenders:
    - stdout
 #日志附着器
loggers:
  zero_blog::service:
    level: INFO
    appenders:
      - info
      - stdout
    additive: true  

  actix_web::middleware:
    level: INFO
    appenders:
      - info
      - stdout
    additive: true  
  
