server:
  address: "127.0.0.1"
  port: 8090
  front_adderss: "http://localhost:8080" ## 前端页面地址 用于跨域访问
mysql:
  address: "127.0.0.1"
  port: 3306
  data_base: "zero_api"
  user_name: "root"
  password: "root"
redis:
  address: "127.0.0.1"
  port: 3306
  db: 1
  password: ""