server:
  host: "127.0.0.1"
  port: 8090
  front_adderss: "http://localhost:8080" ## 前端页面地址 用于跨域访问
mysql:
  host: "127.0.0.1"
  port: 3306
  data_base: "zero_api"
  user_name: "root"
  password: "root"
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  username: ""
  password: ""
  #KEY 过期时间 单位:秒
  ttl: "600"