# log4rs.yaml
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"

  debug:
    kind: rolling_file
    path: "logs/debug.log"
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"  
    policy:
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "logs/debug.{}.log"
        base: 0
        count: 10

  info:
    kind: rolling_file
    path: "logs/info.log"
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}"
    policy:
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "logs/info.{}.log"
        base: 0
        count: 10

#日志 root
root:
  level: INFO
  appenders:
    - stdout
 #日志附着器
loggers:
  rbatis::plugin::intercept_log: #rbatis日志
    level: DEBUG
    appenders:
      - debug
    additive: false 

  zero_blog::service:
    level: INFO
    appenders:
      - info
      - stdout
    additive: false  

  actix_web::middleware:
    level: INFO
    appenders:
      - info
      - stdout
    additive: false  
  
