//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::model::Visitor;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "visitor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub uuid: String,
    pub ip: Option<String>,
    pub ip_source: Option<String>,
    pub os: Option<String>,
    pub browser: Option<String>,
    pub create_time: DateTime,
    pub last_time: DateTime,
    pub pv: Option<i32>,
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl From<Visitor> for Model {
    fn from(value: Visitor) -> Self {
        Self {
            id: value.id,
            uuid: value.uuid,
            ip: value.ip,
            ip_source: value.ip_source,
            os: value.os,
            browser: value.browser,
            create_time: value.create_time,
            last_time: value.last_time,
            pv: value.pv,
            user_agent: value.user_agent,
        }
    }
}
