name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
 
    - name: Cache Rust dependencies
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --all-features
 
    - name: Verify
      run: cargo check --all-features --tests
 
    - name: Build
      run: cargo build --all-features --release
 
    - name: Test
      run: cargo test --all-features
 
    - name: Lint
      run: cargo clippy --all-features -- -D clippy::all
 
    - name: Create release artifact
      if: startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target x86_64-unknown-linux-musl
