name: RUST CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: rustup install stable

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Strip binary
      run: strip "target/release/zero_blog" 
       
    - name: Build archive
      shell: bash
      run: |
          mkdir archive
          cp LICENSE README.MD archive/
          cd archive
          cp "../target/release/zero_blog" ./
          tar -czf "zero-linux.tar.gz" LICENSE README.MD zero_blog

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: zero-linux.tar.gz
        path: archive/zero-linux.tar.gz
