name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: x86_64-unknown-linux-gnu:latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r
    - name: Run tests
      run: cargo test -r
